module load cuda/11.0
echo $LD_LIBRARY_PATH


# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/toydata_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=1024 --config.training.snapshot_freq=2500 --config.training.n_iters=50001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=20 --config.eval.batch_size=1024 --config.eval.num_samples=1024
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/toydata_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --eval_folder=eval --mode=eval --config.eval.begin_ckpt=1 --config.eval.end_ckpt=10 --config.eval.enable_sampling=False --config.eval.batch_size=1024 --config.eval.num_samples=1024
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/mnist_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=128 --config.training.snapshot_freq=100000 --config.training.n_iters=100001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.eval.batch_size=128 --config.eval.num_samples=256
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/binmnist_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=128 --config.training.snapshot_freq=100000 --config.training.n_iters=100001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.eval.batch_size=625 --config.eval.num_samples=256
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/cifar10_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.training.batch_size=128 --config.training.snapshot_freq=100000 --config.training.n_iters=100001 --config.eval.begin_ckpt=19 --config.eval.end_ckpt=19 --config.eval.enable_sampling=True --config.eval.batch_size=128 --config.eval.num_samples=256
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/mnist_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.training.batch_size=128 --config.training.snapshot_freq=10000 --config.training.n_iters=80001 --config.eval.begin_ckpt=16 --config.eval.end_ckpt=16
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/mnist_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=64 --config.training.snapshot_freq=10000 --config.training.n_iters=80001 --config.eval.begin_ckpt=8 --config.eval.end_ckpt=8 --config.training.experiment_name=ve_m10_lat$1d_tuni_kl1e-7 --config.model.latent_input_dim=$1
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ncsnpp/cifar10_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.eval.use_vae_samples=True --config.eval.vae_sample_t=$2 --config.eval.eval_dir_postfix=_t$2_$1 --config.eval.num_samples=49999
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ncsnpp/cifar10_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.eval.use_vae_samples=True --config.eval.vae_sample_t=$2 --config.eval.eval_dir_postfix=_t$2_$1 --config.eval.num_samples=49999
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/my_cifar_large_continuous_vp.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=64 --config.training.snapshot_freq=80000 --config.training.n_iters=80001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.training.experiment_name=c10_vp_trecl_lat$1_lam$2 --config.model.time_dependent_encoder=True --config.model.lambda_reconstr=$2 --config.model.latent_input_dim=$1
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/my_cifar_large_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=64 --config.training.snapshot_freq=80000 --config.training.n_iters=80001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.training.experiment_name=c10_tballarge_lat$1_lam$2 --config.model.time_dependent_encoder=True --config.model.lambda_reconstr_rate=$2 --config.model.latent_input_dim=$1

XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/my_cifar_small_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=train --config.training.batch_size=64 --config.training.snapshot_freq=80000 --config.training.n_iters=80001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.training.experiment_name=$2 --config.model.time_dependent_encoder=True --config.model.latent_input_dim=$1 --config.training.train_clf=True


# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/aedata_deep_continuous_subvp.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.training.batch_size=1024 --config.training.snapshot_freq=100000 --config.training.n_iters=100001 --config.eval.begin_ckpt=1 --config.eval.end_ckpt=1 --config.eval.batch_size=100 --config.eval.num_samples=1024
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 train_mnist_ae.py
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 train_mnist_vae.py
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 train_cifar_vae.py
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 train_mnist_vae_prob.py



# /usr/bin/python3 test.py
