module load cuda/11.0
echo $LD_LIBRARY_PATH


#XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/my_cifar_large_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=both --config.training.batch_size=64 --config.training.snapshot_freq=10000 --config.training.n_iters=300000 --config.eval.begin_ckpt=30 --config.eval.end_ckpt=30 --config.training.experiment_name=ve_cstruc_tstd$2_det$3_lam$4_$1 --config.model.deterministic_latent_input=$3 --config.model.uniform_std_sampling=$2 --config.model.lambda_z_sh=$4 --config.eval.enable_sampling=True
#XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ddpmpp/cifar10_deep_continuous_vp.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.eval.enable_sampling=False --config.eval.enable_latent=True --config.eval.begin_ckpt=19 --config.eval.end_ckpt=19 --config.training.experiment_name=pretrained_vp_c10
# XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ncsnpp/cifar10_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.eval.eval_dir_postfix=_cond$2_steps$3_$1 --config.eval.guidance_factor=$2 --config.eval.n_sampling_steps=$3 --config.eval.conditional_sampling=True --config.eval.num_samples=49999 --config.eval.begin_ckpt=12 --config.eval.end_ckpt=12

#XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ncsnpp/cifar10_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.training.start_checkpoint_dir=checkpoints_pretrained_ve_c10 --config.training.experiment_name=pre_ve_lam-$2_sam-$3_$1 --config.training.lambda_method=$2 --config.training.lambda_method_sampling=$3 --config.eval.num_samples=19999
XLA_FLAGS=--xla_gpu_cuda_data_dir=/is/software/nvidia/cuda-11.0/ /usr/bin/python3 main.py --config=configs/ncsnpp/cifar10_deep_continuous_ve.py --workdir=/home/kabstreiter/score_sde --mode=eval --config.training.start_checkpoint_dir=checkpoints_pretrained_ve_c10 --config.training.experiment_name=pre_ve_lam-lossprop_sam-$2_$1 --config.eval.num_samples=49999
